sudo: required
language: python
jdk: openjdk8
services: docker
matrix:
  fast_finish: true

before_install:
  - docker pull beckerlab/methylscore:latest

install:
  - mkdir /tmp/nextflow && cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow

env:
  - SAMPLES="--SAMPLE_SHEET 'https://github.com/Gregor-Mendel-Institute/test-data/raw/MethylScore/samplesheet.tsv'"
  - SAMPLES="--SAMPLE_SHEET 'https://github.com/Gregor-Mendel-Institute/test-data/raw/MethylScore/samplesheet_bedGraph.tsv' --BEDGRAPH"

script:
  - nextflow run ${TRAVIS_BUILD_DIR} $SAMPLES -profile testing,docker
