name: MethylScore
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::numpy=1.19.1
  - bioconda::samtools=1.9
  - bioconda::bedtools=2.29.2
  - bioconda::picard-slim=2.26.8
  - bioconda::MethylDackel=0.4.0
