name: MethylScore
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::numpy=1.19.1
  - bioconda::perl=5.28.1
  - bioconda::perl-app-cpanminus=1.7044
  - bioconda::samtools=1.9
  - bioconda::tabix=0.2.6
  - bioconda::bamtools=2.5.1
  - bioconda::bedtools=2.29.2
  - bioconda::picard=2.23.3
  - bioconda::MethylDackel=0.4.0
  - bioconda::methylextract=1.9.1
