name: MethylScore
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - samtools=1.9
  - tabix=0.2.5
  - bamtools=2.5.1
  - bedtools=2.27.1
  - picard=2.18.11
  - scipy=1.2.1
  - perl=5.26.2
  - methylextract=1.9.1
  - MethylDackel=0.4.0
