name: Docker Container

on:
  push:
    paths:
      - 'containers/base/Dockerfile'
      - 'containers/base/environment.yaml'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: beckerlab/methylscore
          tag_with_ref: true